# Generated by Django 2.2.4 on 2019-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=32)),
                ('create_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
        ),
    ]
